### ISSUE TITLE
EDMCOverlay exception: There are no context policies.

### ISSUE THREAD

**Issue by seldonlabs** [inorton/EDMCHits#12]
I had HITS working for a day but now I have this exception with EDMCOverlay.exe:

```
2018-01-06T23:22:23 OverlayRenderer: Loading fonts..
2018-01-06T23:22:23 OverlayJsonServer: JSON server thread startup
2018-01-06T23:22:23 EDMCOverlay: unhandled exception!!: Name:EDMCOverlay.exe
There are no context policies.
 System.UnhandledExceptionEventArgs
2018-01-06T23:22:23 EDMCOverlay:    at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.get_HasExited()
   at EDMCOverlay.OverlayRenderer.StartUpdate()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

**Comment by seldonlabs** [comment]
The exception is thrown here:
https://i.imgur.com/497BcWg.jpg

**Comment by seldonlabs** [comment]
Fixed after a reboot so maybe this exception is aleatory.

**Comment by inorton** [comment]
Very odd.  It looks like one of those exceptions I just can't catch
